const express = require('express');
const { supabase } = require('../supabaseClient');
const { requireSupabaseAuth } = require('../middleware/supabaseAuth');

const router = express.Router();
const clean = (value, max = 4000) => String(value ?? '').trim().slice(0, max);
const uuid = value => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value || ''));
const fail = (res, status, message, code = 'operational_error') => res.status(status).json({ success: false, code, message });
const enabled = () => process.env.TSHOW_OPERATIONAL_FEATURES === 'true' || process.env.NODE_ENV !== 'production';
const guard = (req, res, next) => enabled() ? next() : fail(res, 503, 'Las funciones operativas están temporalmente desactivadas.', 'feature_disabled');

async function access(req, projectId, write = false) {
  if (!uuid(projectId)) return null;
  const { data: project } = await supabase.from('tshow_projects').select('id,owner_id,organization_id,document_version,payload').eq('id', projectId).is('deleted_at', null).maybeSingle();
  if (!project) return null;
  if (project.owner_id === req.user.id) return { project, role: 'owner' };
  const { data: member } = await supabase.from('tshow_project_members').select('role').eq('project_id', projectId).eq('user_id', req.user.id).maybeSingle();
  if (member) return (!write || member.role === 'editor') ? { project, role: member.role } : null;
  if (project.organization_id) {
    const { data: org } = await supabase.from('tshow_organization_members').select('role').eq('organization_id', project.organization_id).eq('user_id', req.user.id).maybeSingle();
    if (org && (!write || ['owner','admin'].includes(org.role))) return { project, role: org.role };
  }
  return null;
}
const canManage = a => a && ['owner','admin'].includes(a.role);
const canWrite = a => a && ['owner','admin','editor'].includes(a.role);
const audit = (projectId, actorId, action, metadata = {}) => supabase.from('tshow_audit_log').insert({ project_id: projectId, actor_id: actorId, action, metadata });

router.get('/projects/:id/production', requireSupabaseAuth, guard, async (req, res) => {
  const a = await access(req, req.params.id); if (!a) return fail(res, 403, 'No tienes acceso operativo a este evento.', 'forbidden');
  const [areas, tasks, artists, appearances, notices] = await Promise.all([
    supabase.from('tshow_project_areas').select('*').eq('project_id', req.params.id).eq('status','active').order('name'),
    supabase.from('tshow_tasks').select('*').eq('project_id', req.params.id).order('due_at'),
    supabase.from('tshow_artists').select('*').eq('project_id', req.params.id).order('name'),
    supabase.from('tshow_artist_appearances').select('*').eq('project_id', req.params.id).order('updated_at',{ascending:false}),
    supabase.from('tshow_operational_notices').select('id,title,body,block_id,area_id,created_by,created_at').eq('project_id', req.params.id).order('created_at',{ascending:false}).limit(30)
  ]);
  const errors = [areas,tasks,artists,appearances,notices].find(x => x.error); if (errors) return fail(res, 500, 'No se pudo cargar el espacio operativo.', 'service_unavailable');
  res.json({ success:true, enabled:true, serverTime:new Date().toISOString(), project:{ id:a.project.id, documentVersion:a.project.document_version }, data:{ areas:areas.data||[], tasks:tasks.data||[], artists:artists.data||[], appearances:appearances.data||[], notices:notices.data||[] }, capabilities:{ manageAreas:canManage(a), editOperational:canWrite(a), createRehearsal:canManage(a) } });
});

router.get('/projects/:id/areas', requireSupabaseAuth, guard, async (req,res)=>{ const a=await access(req,req.params.id); if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden'); const {data,error}=await supabase.from('tshow_project_areas').select('*,tshow_project_area_members(user_id,can_update)').eq('project_id',req.params.id).order('name'); if(error)return fail(res,500,'No se pudieron cargar las áreas.'); res.json({success:true,data:data||[]}); });
router.post('/projects/:id/areas', requireSupabaseAuth, guard, async (req,res)=>{ const a=await access(req,req.params.id,true); if(!canManage(a))return fail(res,403,'Solo el propietario o administrador puede gestionar áreas.','forbidden'); const name=clean(req.body.name,100); const key=clean(req.body.areaKey,60).toLowerCase().replace(/[^a-z0-9_-]/g,'-'); if(name.length<2||key.length<2)return fail(res,400,'Nombre y clave de área son obligatorios.','validation_error'); const {data,error}=await supabase.from('tshow_project_areas').insert({project_id:req.params.id,name,area_key:key,created_by:req.user.id}).select().single(); if(error)return fail(res,409,'El área ya existe o no es válida.','conflict'); await audit(req.params.id,req.user.id,'operational.area.created',{areaId:data.id}); res.status(201).json({success:true,data}); });

router.get('/projects/:id/technical-cues', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const {data,error}=await supabase.from('tshow_technical_cues').select('*').eq('project_id',req.params.id).order('updated_at',{ascending:false});if(error)return fail(res,500,'No se pudieron cargar las indicaciones.');res.json({success:true,data:data||[]});});
router.post('/projects/:id/technical-cues', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id,true);if(!canWrite(a))return fail(res,403,'No tienes permisos para editar indicaciones.','forbidden');if(!uuid(req.body.areaId))return fail(res,400,'Área inválida.','validation_error');const patch={project_id:req.params.id,block_id:uuid(req.body.blockId)?req.body.blockId:null,area_id:req.body.areaId,body:clean(req.body.body,4000),updated_by:req.user.id};const {data,error}=await supabase.from('tshow_technical_cues').upsert(patch,{onConflict:'project_id,block_id,area_id'}).select().single();if(error)return fail(res,400,'No se pudo guardar la indicación.','validation_error');await audit(req.params.id,req.user.id,'operational.cue.updated',{cueId:data.id});res.json({success:true,data});});

router.get('/projects/:id/readiness', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const {data,error}=await supabase.from('tshow_block_area_readiness').select('*,tshow_project_areas(name,area_key),tshow_project_blocks(title,position,start_time)').eq('project_id',req.params.id).order('updated_at',{ascending:false});if(error)return fail(res,500,'No se pudo cargar la preparación.');res.json({success:true,data:data||[]});});
router.patch('/projects/:id/readiness/:readinessId', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req.params.id?req:req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const status=['pending','preparing','ready','problem','not_applicable'].includes(req.body.status)?req.body.status:null;if(!status)return fail(res,400,'Estado de preparación inválido.','validation_error');const {data:row}=await supabase.from('tshow_block_area_readiness').select('id,area_id').eq('id',req.params.readinessId).eq('project_id',req.params.id).maybeSingle();if(!row)return fail(res,404,'Preparación no encontrada.','not_found');let allowed=canWrite(a);if(!allowed){const {data:m}=await supabase.from('tshow_project_area_members').select('can_update').eq('area_id',row.area_id).eq('user_id',req.user.id).maybeSingle();allowed=Boolean(m?.can_update);}if(!allowed)return fail(res,403,'No tienes permiso para actualizar esta área.','forbidden');const {data,error}=await supabase.from('tshow_block_area_readiness').update({status,note:clean(req.body.note,2000),confirmed_by:req.user.id,confirmed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',row.id).select().single();if(error)return fail(res,400,'No se pudo actualizar la preparación.','validation_error');await audit(req.params.id,req.user.id,'operational.readiness.updated',{readinessId:row.id,status});res.json({success:true,data});});

router.get('/projects/:id/artists', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const {data,error}=await supabase.from('tshow_artists').select('*,tshow_artist_appearances(*)').eq('project_id',req.params.id).order('name');if(error)return fail(res,500,'No se pudieron cargar los artistas.');res.json({success:true,data:data||[]});});
router.post('/projects/:id/artists', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id,true);if(!canWrite(a))return fail(res,403,'No tienes permisos para gestionar artistas.','forbidden');const name=clean(req.body.name,180);if(name.length<2)return fail(res,400,'El nombre del artista es obligatorio.','validation_error');const {data,error}=await supabase.from('tshow_artists').insert({project_id:req.params.id,name,kind:clean(req.body.kind,40)||'artist',notes:clean(req.body.notes,4000),created_by:req.user.id}).select().single();if(error)return fail(res,400,'No se pudo crear el artista.','validation_error');res.status(201).json({success:true,data});});

router.get('/projects/:id/notices', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const {data,error}=await supabase.from('tshow_operational_notices').select('*,tshow_operational_notice_recipients(*)').eq('project_id',req.params.id).order('created_at',{ascending:false}).limit(100);if(error)return fail(res,500,'No se pudieron cargar los avisos.');res.json({success:true,data:data||[]});});
router.post('/projects/:id/notices', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id,true);if(!canWrite(a))return fail(res,403,'No tienes permisos para enviar avisos.','forbidden');const title=clean(req.body.title,180),body=clean(req.body.body,2000);if(title.length<2||!body)return fail(res,400,'Título y mensaje son obligatorios.','validation_error');const {data,error}=await supabase.from('tshow_operational_notices').insert({project_id:req.params.id,title,body,block_id:uuid(req.body.blockId)?req.body.blockId:null,area_id:uuid(req.body.areaId)?req.body.areaId:null,created_by:req.user.id,idempotency_key:clean(req.body.idempotencyKey,120)||null}).select().single();if(error?.code==='23505')return res.status(200).json({success:true,data:{idempotent:true}});if(error)return fail(res,400,'No se pudo enviar el aviso.','validation_error');const recipients=Array.isArray(req.body.userIds)?req.body.userIds.filter(uuid).slice(0,100):[];if(recipients.length){const {error:recipientError}=await supabase.from('tshow_operational_notice_recipients').insert(recipients.map(user_id=>({notice_id:data.id,user_id})));if(recipientError)return fail(res,400,'El aviso se creó pero no se pudieron asignar destinatarios.','partial_failure');}await audit(req.params.id,req.user.id,'operational.notice.created',{noticeId:data.id});res.status(201).json({success:true,data});});
router.post('/projects/:id/notices/:noticeId/confirm', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const {data,error}=await supabase.from('tshow_operational_notice_recipients').update({confirmed_at:new Date().toISOString()}).eq('notice_id',req.params.noticeId).eq('user_id',req.user.id).select().single();if(error)return fail(res,403,'Este aviso no está dirigido a tu cuenta.','forbidden');res.json({success:true,data});});

router.get('/projects/:id/rehearsals', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id);if(!a)return fail(res,403,'No tienes acceso a este evento.','forbidden');const {data,error}=await supabase.from('tshow_rehearsals').select('*').eq('project_id',req.params.id).order('created_at',{ascending:false});if(error)return fail(res,500,'No se pudieron cargar los ensayos.');res.json({success:true,data:data||[]});});
router.post('/projects/:id/rehearsals', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id,true);if(!canManage(a))return fail(res,403,'Solo el propietario o administrador puede crear ensayos.','forbidden');const name=clean(req.body.name,180);if(name.length<2)return fail(res,400,'El nombre del ensayo es obligatorio.','validation_error');const {data,error}=await supabase.from('tshow_rehearsals').insert({project_id:req.params.id,name,source_document_version:a.project.document_version,created_by:req.user.id}).select().single();if(error)return fail(res,400,'No se pudo crear el ensayo.','validation_error');await audit(req.params.id,req.user.id,'operational.rehearsal.created',{rehearsalId:data.id});res.status(201).json({success:true,data});});

router.post('/projects/:id/timing-adjustments/preview', requireSupabaseAuth, guard, async(req,res)=>{const a=await access(req,req.params.id,true);if(!canWrite(a))return fail(res,403,'No tienes permisos para proponer ajustes.','forbidden');const blocks=Array.isArray(req.body.blocks)?req.body.blocks.map((b,index)=>({index,title:clean(b.title,180),originalMinutes:Math.max(1,Number(b.originalMinutes)||0),proposedMinutes:Math.max(1,Number(b.proposedMinutes)||0),fixed:Boolean(b.fixed)})):[];if(!blocks.length)return fail(res,400,'Debes incluir bloques para simular.','validation_error');const preview={blocks,deltaMinutes:blocks.reduce((n,b)=>n+b.proposedMinutes-b.originalMinutes,0),createdAt:new Date().toISOString()};const {data,error}=await supabase.from('tshow_timing_adjustments').insert({project_id:req.params.id,base_document_version:a.project.document_version,preview,created_by:req.user.id}).select().single();if(error)return fail(res,400,'No se pudo guardar la simulación.','validation_error');res.status(201).json({success:true,data});});

module.exports = router;
