(async () => {
  const profile = await Auth.requireGlobalRole(['platform_admin']); if (!profile) return;
  const $ = id => document.getElementById(id); const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const moduleLabels = { command_center:'Centro de comando', approvals:'Aprobaciones', incidents:'Incidentes', guest_passes:'Pases de invitado', teleprompter:'Teleprompter', erp:'ERP', advanced_exports:'Exportaciones avanzadas', integrations:'Integraciones' };
  let accounts = []; let selected = null;
  const show = (node, text, error = false) => { node.textContent = text; node.hidden = false; node.dataset.status = error ? 'error' : 'success'; };
  $('whoami').textContent = `${profile.first_name || ''} ${profile.last_name || ''}`.trim() || profile.email || '—';
  $('logoutButton')?.addEventListener('click', () => Auth.logout());
  async function loadPlans() { const result = await Auth.api('/api/admin/plans'); $('planCount').textContent = (result.data || []).filter(p => p.active).length; $('plans').innerHTML = (result.data || []).map(plan => `<form data-id="${esc(plan.id)}" class="auth-form" style="margin-bottom:16px"><strong>${esc(plan.name)} · ${plan.interval === 'month' ? 'Mensual' : 'Anual'}</strong><div class="form-row"><input class="form-control" name="name" value="${esc(plan.name)}"><input class="form-control" name="amount" type="number" min="1" placeholder="Precio CLP" value="${plan.amount_clp || ''}"><input class="form-control" name="limit" type="number" min="1" placeholder="Límite de eventos" value="${plan.project_limit || ''}"></div><label><input name="active" type="checkbox" ${plan.active ? 'checked' : ''}> Disponible para vender</label><button class="btn btn-primary">Guardar plan</button></form>`).join('') || '<p class="admin-muted">No hay planes configurados.</p>'; document.querySelectorAll('#plans form').forEach(form => form.onsubmit = async e => { e.preventDefault(); const data = new FormData(form); try { await Auth.api(`/api/admin/plans/${form.dataset.id}`, {method:'PATCH',body:JSON.stringify({name:data.get('name'),amount_clp:data.get('amount')?Number(data.get('amount')):null,project_limit:data.get('limit')?Number(data.get('limit')):null,active:data.get('active')==='on'})}); show($('message'),'Plan actualizado.'); } catch (error) { show($('message'),error.message,true); } }); }
  const planLabel = plan => ({free:'Gratis',pro:'Pro',max:'Max',enterprise:'Empresa'}[plan] || plan || '—');
  const statusLabel = status => ({free:'Gratis',active:'Activa',read_only:'Solo lectura',expired:'Vencida',cancelled:'Cancelada',inactive:'Sin suscripción'}[status] || status || '—');
  const dateLabel = value => value ? new Date(value).toLocaleString('es-CL') : '—';
  async function loadAccounts() { const q = $('accountSearch').value.trim(); const result = await Auth.api(`/api/admin/accounts${q ? `?q=${encodeURIComponent(q)}` : ''}`); accounts = result.data || []; $('accountCount').textContent = accounts.length; $('projectCount').textContent = accounts.reduce((sum,a)=>sum+(a.ownedCount||0),0); $('accounts').innerHTML = accounts.length ? `<table class="admin-table"><thead><tr><th>Cuenta registrada</th><th>Rol</th><th>Rango / estado</th><th>Uso</th><th>Pago / vigencia</th><th></th></tr></thead><tbody>${accounts.map(a => { const fullName=`${a.first_name||''} ${a.last_name||''}`.trim()||a.email; const manual=a.entitlementSource==='manual'; return `<tr><td><strong>${esc(fullName)}</strong><br><span class="admin-muted">${esc(a.email)}${a.phone?` · ${esc(a.phone)}`:''}<br>${a.rut?`RUT ${esc(a.rut)}`:''}${a.organization?` · ${esc(a.organization)}`:''}</span></td><td>${esc(a.role||'account_owner')}<br><span class="admin-muted">Alta: ${esc(dateLabel(a.created_at))}</span></td><td><strong>${esc(planLabel(a.plan))}</strong><br><span class="admin-badge ${manual?'manual':'paid'}">${manual?'Asignación manual':a.subscriptionStatus==='active'?'Suscripción activa':'Cuenta estándar'}</span><br><span class="admin-muted">${esc(statusLabel(a.status))}</span></td><td>${a.ownedCount||0} / ${a.limit===null?'∞':a.limit}<br><span class="admin-muted">${a.remaining===null?'Ilimitado':`${a.remaining} disponibles`}</span></td><td><span class="admin-muted">${a.lastPaymentAt?`Último pago: ${esc(dateLabel(a.lastPaymentAt))}`:'Sin pagos registrados'}<br>${a.currentPeriodEnd?`Período: ${esc(dateLabel(a.currentPeriodEnd))}`:'Sin vencimiento comercial'}</span></td><td><button class="btn btn-secondary" data-account="${esc(a.id)}">Ver ficha</button></td></tr>`; }).join('')}</tbody></table>` : '<p class="admin-muted">No se encontraron cuentas.</p>'; document.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>openDetail(accounts.find(a=>a.id===b.dataset.account))); }
  const inputDate = value => value ? new Date(value).toISOString().slice(0,16) : '';
  async function openDetail(account) { if (!account) return; selected=account; const result=await Auth.api(`/api/admin/accounts/${account.id}/history`); const features=await Auth.api(`/api/admin/accounts/${account.id}/features`); $('accountTitle').textContent=`${account.first_name||''} ${account.last_name||''}`.trim()||account.email; $('accountMeta').textContent=`${account.email} · ${account.phone||'Teléfono no informado'} · ${account.rut||'RUT no informado'} · ${account.organization||'Organización no informada'} · ID ${account.id}`; $('accountCommercial').textContent=`Origen del acceso: ${account.entitlementSource==='manual'?'asignación manual del superadmin':'suscripción o plan estándar'} · Suscripción: ${account.subscriptionPlan||'sin plan pagado'} (${statusLabel(account.subscriptionStatus)}) · Último pago: ${dateLabel(account.lastPaymentAt)}`; const form=$('accountForm'); form.plan.value=account.plan;form.status.value=account.status;form.customLimit.value=account.customLimit||'';form.startsAt.value=inputDate(account.startsAt);form.expiresAt.value=inputDate(account.expiresAt);form.reason.value=''; $('accountModules').innerHTML=Object.entries(moduleLabels).map(([key,label])=>{const enabled=features.data?.find(f=>f.feature_key===key)?.enabled;return `<label><input type="checkbox" data-feature="${key}" ${enabled?'checked':''}> ${label}</label>`}).join(''); $('accountHistory').innerHTML=(result.data||[]).map(h=>`<article><strong>${esc(h.new_plan||'Módulo')}</strong> · ${esc(h.new_status||'')}</strong><br><span class="admin-muted">${new Date(h.created_at).toLocaleString('es-CL')} · ${esc(h.reason||'')}</span></article>`).join('')||'<span class="admin-muted">Sin cambios registrados.</span>'; $('detailMessage').textContent=''; $('accountDialog').showModal(); }
  $('accountForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);const payload={plan:data.get('plan'),status:data.get('status'),customLimit:data.get('customLimit')?Number(data.get('customLimit')):null,startsAt:data.get('startsAt')?new Date(data.get('startsAt')).toISOString():null,expiresAt:data.get('expiresAt')?new Date(data.get('expiresAt')).toISOString():null,reason:data.get('reason')};try{$('accountSave').disabled=true;await Auth.api(`/api/admin/accounts/${selected.id}/entitlement`,{method:'PATCH',body:JSON.stringify(payload)});for(const box of document.querySelectorAll('[data-feature]'))await Auth.api(`/api/admin/accounts/${selected.id}/features/${box.dataset.feature}`,{method:'PUT',body:JSON.stringify({enabled:box.checked,reason:payload.reason})});$('accountDialog').close();await loadAccounts();show($('accountMessage'),'Cuenta actualizada y auditada.');}catch(error){$('detailMessage').textContent=error.message||'No se pudo guardar.';}finally{$('accountSave').disabled=false;}};
  $('accountRefresh').onclick=loadAccounts; $('accountSearch').oninput=()=>loadAccounts(); await Promise.all([loadPlans(),loadAccounts()]);
})().catch(error => { const node=document.getElementById('accountMessage'); if(node){node.hidden=false;node.textContent=error.message||'No se pudo cargar la administración.';} });
